### ISSUE TITLE
aws-sdk support for versions 1.0series and 2.0 series

### ISSUE THREAD

**Issue by kunday** [kunday/cloudformer#16]
Currently, 2.0 series doesn't seem to work.

**Comment by grayudu** [comment]
i an seeing this error. is it because of 2.0?
NameError: uninitialized constant Stack::AWS

**Comment by kunday** [comment]
@grayudu Most likely, can you paste the stack trace please?

**Comment by grayudu** [comment]
rake --trace -T
rake aborted!
NameError: uninitialized constant Stack::AWS
/Library/Ruby/Gems/2.0.0/gems/cloudformer-0.0.17/lib/cloudformer/stack.rb:14:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cloudformer-0.0.17/lib/cloudformer/tasks.rb:9:in `new'
/Library/Ruby/Gems/2.0.0/gems/cloudformer-0.0.17/lib/cloudformer/tasks.rb:9:in `initialize'
/Users/grayudu/aws-learnings/cloudformer/Rakefile:2:in `new'
/Users/grayudu/aws-learnings/cloudformer/Rakefile:2:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/bin/rake:23:in `load'
/usr/bin/rake:23:in `<main>'

**Comment by kunday** [comment]
Hi @grayudu yes, this is because the aws-sdk version you are using is the 2.0 series. I was able to replicate the bug locally. Looks like the aws-sdk is not locked to 1. series here  https://github.com/kunday/cloudformer/blob/master/cloudformer.gemspec#L24 .

Temporary work around would be set the aws-sdk version to 1. series in your project's Gemfile/Gemfile.lock 

I'll look into extending the support to 2.0 series soon.

**Comment by kunday** [comment]
@grayudu This has been fixed and merged to master https://github.com/kunday/cloudformer/pull/17

**Comment by grayudu** [comment]
i did following changes to get rake tasks list
update aws-sdk-v1 two files 
cloudformer.gemspec
stack.rb
# rake -T
/Users/grayudu/aws-learnings/cloudformer/cloudformer.gemspec:16: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
rake apply          # Apply Stack with Cloudformation script and parameters
rake build          # Build cloudformer-0.0.17.gem into the pkg directory
rake delete         # Delete stack from CloudFormation
rake events         # Get the recent events from the stack
rake force_delete   # Delete stack after stopping all instances
rake install        # Build and install cloudformer-0.0.17.gem into system gems
rake install:local  # Build and install cloudformer-0.0.17.gem into system gems without network access
rake outputs        # Get the outputs of stack
rake recreate       # Recreate stack
rake release        # Create tag v0.0.17 and build and push cloudformer-0.0.17.gem to Rubygems
rake start          # Start EC2 instances in stack
rake status         # Get the deployed app status
rake stop           # Stop EC2 instances in stack
rake validate       # Validate the Stack

**Comment by grayudu** [comment]
I am currently seeing this error..
# rake apply
/Users/grayudu/aws-learnings/cloudformer/cloudformer.gemspec:16: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
Initializing stack creation...
rake aborted!
AWS::Core::OptionGrammar::FormatError: expected enumerable value for option capabilities
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/option_grammar.rb:240:in `validate'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/option_grammar.rb:590:in `block in validate'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/option_grammar.rb:586:in `each'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/option_grammar.rb:586:in `validate'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/option_grammar.rb:601:in `request_params'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/query_request_builder.rb:37:in `populate_request'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:740:in `block (2 levels) in define_client_method'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:560:in `build_request'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:491:in `block (3 levels) in client_request'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/response.rb:175:in `call'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/response.rb:175:in `build_request'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/response.rb:114:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:203:in `new'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:203:in `new_response'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:490:in `block (2 levels) in client_request'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:391:in `log_client_request'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:477:in `block in client_request'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:373:in `return_or_raise'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:476:in `client_request'
(eval):3:in `create_stack'
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.64.0/lib/aws/cloud_formation/stack_collection.rb:146:in `create'
/Users/grayudu/aws-learnings/cloudformer/lib/cloudformer/stack.rb:168:in `create'
/Users/grayudu/aws-learnings/cloudformer/lib/cloudformer/stack.rb:47:in `apply'
/Users/grayudu/aws-learnings/cloudformer/lib/cloudformer/tasks.rb:38:in `block in define_create_task'
Tasks: TOP => apply
(See full trace by running task with --trace)
